version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_managements
    ports:
      - "3306:3306"
